/** Frontend mirror of backend PermissionKeys - used to hide unauthorised menu items. */
export const P = {
  VIEW_ALL_VEHICLES: 'view_all_vehicles',
  VIEW_LIVE_LOCATION: 'view_live_location',
  MANAGE_DEVICES: 'manage_devices',
  CREATE_DEVICE: 'create_device',
  DELETE_DEVICE: 'delete_device',
  RENEW_DEVICE: 'renew_device',
  MANAGE_USERS: 'manage_users',
  MANAGE_DRIVERS: 'manage_drivers',
  MANAGE_GROUPS: 'manage_groups',
  MANAGE_PROJECTS: 'manage_projects',
  MANAGE_GEOFENCES: 'manage_geofences',
  SEND_COMMANDS: 'send_commands',
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',
  MANAGE_REPORT_SCHEDULES: 'manage_report_schedules',
  MANAGE_NOTIFICATIONS: 'manage_notifications',
  MANAGE_BILLING: 'manage_billing',
  MANAGE_EXPIRY: 'manage_expiry',
  VIEW_POINTS: 'view_points',
  MANAGE_TENANTS: 'manage_tenants',
  MANAGE_BRANDING: 'manage_branding',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  MANAGE_SERVER_SETTINGS: 'manage_server_settings',
  DRIVER_DUTY: 'driver_duty',
} as const;
